name: Block PR to main

on:
  pull_request:
    branches: [ main ]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Close pull request
        uses: peter-evans/close-pull-request@v1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          comment: |
            Pull requests to `main` are not allowed.
            Please target your PR to `dev` branch instead.
          delete-branch: false