name: Security Check

on:
    pull_request:
      branches: [develop]

jobs:
  sast:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/owasp-top-ten
            p/python

  sca:
    name: SCA - Trivy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library'
          scanners: 'vuln'

      - name: Trivy scan summary
        if: always()
        run: |
          echo "Trivy vulnerability scan completed"
          echo "Check the logs above for any vulnerabilities found"

  license:
    name: License Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check license compatibility
        uses: apache/skywalking-eyes@main
        with:
          config: .licenserc.yaml

      - name: Simple License Check
        run: |
          echo "Checking for LICENSE file..."
          if [ -f "LICENSE" ]; then
            echo "LICENSE file found"
            head -5 LICENSE
          else
            echo "No LICENSE file found"
            exit 1
          fi

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [sast, sca, license]
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Security Summary
        run: |
          echo "Security Check Summary"
          echo "=========================="
          echo "SAST (Semgrep): ${{ needs.sast.result }}"
          echo "SCA (Trivy): ${{ needs.sca.result }}"
          echo "License Check: ${{ needs.license.result }}"
          echo ""
          echo "Results:"
          if [ "${{ needs.sast.result }}" = "success" ]; then
            echo "SAST scan completed successfully"
          else
            echo "SAST scan failed or found issues"
          fi
          
          if [ "${{ needs.sca.result }}" = "success" ]; then
            echo "SCA scan completed successfully"
          else
            echo "SCA scan failed or found vulnerabilities"
          fi
          
          if [ "${{ needs.license.result }}" = "success" ]; then
            echo "License check completed successfully"
          else
            echo "License check failed or found issues"
          fi 